### ISSUE TITLE
'manualAttach' (a nil value)

### ISSUE THREAD

**Issue by Gecko774** [4c65736975/noMoreAutoLift#1]
Hello,

Unfortunately, as soon as this mod is activated, the game no longer loads.

In connection with "Manual Attach" the following error occurs in the log when loading:

.../Documents/My Games/FarmingSimulator2022/mods/FS22_NoMoreAutoLift/src/AttachFix.lua:139: attempt to index global 'manualAttach' (a nil value)

Best regards

**Comment by 4c65736975** [comment]
Latest release (v1.0.0.3), I didn't notice any problems. Please download and replace it with new version. Create new issue if problem still occures.
