### ISSUE TITLE
Second Test "a nil value"

### ISSUE THREAD

**Issue by Gecko774** [4c65736975/noMoreAutoLift#2]
Hello,

I just tried it again and I noticed the following.

-the new version 1.0.0.3 with manual attach from Github (version 2.1) does not load with the text "FarmingSimulator2022/mods/FS22_NoMoreAutoLift/src/NoMoreAutoLift.lua:141: attempt to index upvalue 'manualAttach' (a nil value)"

-the new version 1.0.0.3 with manual attach from Modhub (2.0)
is loaded without error but on the Silverrun Forrest there is also a Lua error: FarmingSimulator2022/mods/FS22_NoMoreAutoLift/src/NoMoreAutoLift.lua:154: attempt to index global 'self' (a nil value)

This happens when you want to hitch the Volvo with the winch to the starting vehicles (new savegame).
He connects the cable winch directly.
The PTO shaft and the cables are automatically connected without pressing a button.

I am attaching the logs from both attempts. Errors can be seen at the bottom.

It's only Easy Dev as a mod, otherwise vanilla

Best regards

[log manual attach 2.0.txt](https://github.com/4c65736975/FS22_NoMoreAutoLift/files/10700030/log.manual.attach.2.0.txt)

[log manual attach 2.1.txt](https://github.com/4c65736975/FS22_NoMoreAutoLift/files/10700035/log.manual.attach.2.1.txt)

**Comment by 4c65736975** [comment]
FarmingSimulator2022/mods/FS22_NoMoreAutoLift/src/NoMoreAutoLift.lua:154: attempt to index global 'self' (a nil value) - fixed

Unfortunately, I do not have version 2.1.0.0 manual attach and I can't find it, if you could send it to me, I will be able to check why the second error occurs.

**Comment by Gecko774** [comment]
Attached is version 2.1 from Github with the changes from stijnwop from 02/16/2022.

But I think that most people use version 2.0 from Modhub (11/30/21) where the error occurs as described above.

I tested the whole thing again with the launch vehicles on the Erlengrat. There are no errors in the starting vehicles and devices.

Only if you try to attach the standard cable winch Tajfun EGV 65 from the Plantinum Expansion by Giants does the Lua error appear as in the log 2.0.


[FS22_manualAttach.zip](https://github.com/4c65736975/FS22_NoMoreAutoLift/files/10701884/FS22_manualAttach.zip)

The zip file is from the code button of stijnwop -> Download zip

Version number is displayed ingame on 2.1 not in the moddesc

https://github.com/stijnwop/manualAttach

**Comment by 4c65736975** [comment]
The error was caused by manualAttach version 2.1.0.0. The latest version (v1.0.0.3) has been updated, I did not notice any problems. Download and replace it with the new version.

**Comment by Gecko774** [comment]
Wow that was fast

Now it works perfectly with both versions.

Thanks very much.
