### ISSUE TITLE
Problem with Kverneland PW 100 - 12 Plow when this mod is active.

### ISSUE THREAD

**Issue by essence25** [4c65736975/noMoreAutoLift#3]
When using the noMoreAutoLift mod(any versions) the Kverneland PW 100 -  12 Plow cannot be unfolded or used. It completely disables the possibility to unfold it. It sits low on the floor, its tires will not even spin when pulled and error messages such as Plow cannot be used because it is not lifted. It cannot be manually lifted since there is no option for that. It does that automatically upon attaching. 
Perhaps you can specify the vehicles this mod should affect or exclude certain tools etc. 
Let me know if you can reproduce it. Just buy the RED plow and try to attach and use it. 
Thank you!

**Comment by 4c65736975** [comment]
The version available on github solves this problem (v.1.0.0.4)
