### ISSUE TITLE
Already attached and lowered front mower implement is lifted on game load

### ISSUE THREAD

**Issue by Gordon-Dry** [4c65736975/noMoreAutoLift#7]
As this just happens and there is nothing suspicious logged I only can assume that this behaviour has something to do with this mod.

I have mowing implements back and front, I stop mowing, turn off the engine, exit the vehicle, save the game and quit.
Then I load the game, still standing next to the vehicle because of FS22_savePlayerPosition and so I can witness that the front mower implement is lifted incl. animation sound, although the engine is off.
After entering the vehicle - manually starting the engine - I have to press "V" twice to make the implement move back down.

**Comment by 4c65736975** [comment]
Should I understand that the machine was lowered, and after re-entering the game it is automatically raised?

**Comment by Gordon-Dry** [comment]
Yes.

**Comment by 4c65736975** [comment]
I'll check it. Does this issue occur in the current version (1.0.0.6)?  But I think it might be a problem with the default specialization in the game, because I had a similar problem with another script that I created for me and I needed to tweak some specializations to make it work.

**Comment by Gordon-Dry** [comment]
Yes, 1.0.0.6

**Comment by 4c65736975** [comment]
> Yes, 1.0.0.6

After checking, this problem already occurs in the original version of the game, i.e. without any modifications. This is a game bug.
